### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by christensenmichael0**
@Bobfrat I believe that its pretty standard to include a lock file but lets see if the warnings go away with this commit..

https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494

In this case it seems that dependencies of other modules were responsible for the security warnings so it's out of our control.

### CODE REVIEW

**Comment by Bobfrat** [comment]
Well that will certainly suppress the warning message but doesn't address the security vulnerabilities. Does upgrading to latest versions of the responsible packages fix the vulnerabilities?

**Comment by christensenmichael0** [comment]
I can give that a shot.. is there a way to test that the upgrades haven't broken something else without manually clicking around in the browser?

**Comment by Bobfrat** [comment]
No, you'll have to click around. The sites pretty basic. Mostly hyperlinks.

**Comment by christensenmichael0** [comment]
@Bobfrat @kellydesent can you guys give this a spin. Seems to be working normally when running with node. The Docker build looks like its missing styling but that issue also appears on master so I don't think it's related to my work here.

**Comment by Bobfrat** [comment]
Looks good to me.

**Pull request merged**
