### PR TITLE
search bar updated

### PR DESCRIPTION
**Pull request by kellydesent**

### CODE REVIEW

**Comment by Bobfrat** [comment]
Addresses https://github.com/ioos/ioos-us/issues/223

**Comment by mwengren** [comment]
@Bobfrat Is there a way to preview changes to the ioos.us sites for PRs like these?  In this case, can't really tell what the change is if I wanted to provide input.

**Comment by Bobfrat** [comment]
Yeah theres a couple options. I could deploy the updates to a dev server for you to test or you could spin up the repo on your machine.

**Comment by Bobfrat** [comment]
@mwengren if you have docker its a pretty easy setup:
1. Check out master branch
2. `docker build -t ioos-us .`
3. `docker run -d -p 3000:3000 ioos-us`
4. Navigate to http://localhost:3000

**Comment by mwengren** [comment]
@Bobfrat Thanks.  These steps look a little different than on the Readme (probably should have looked there first, oops).  I see there's two options to run it 1) node, 2) Docker.  But, can the full Docker instructions be added to the Readme for this and other ioos.us sites?  

I'll give it a go at some point, no need to deploy a dev server just for this.  I asked just because I hadn't seen the new changes deployed on the live site yet even after this was merged, and I wasn't sure what the process was for that/curious to see what changed.

**Pull request merged**
