### PR TITLE
Update links with explicit protocols

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Now when I hit https://sensors.ioos.us/, I don't get that error message, but just this "Loading" screen, which seems stalled:


Is that expected or is there something I have to do on my end to clear some browser setting?

**Comment by shane-axiom** [comment]
@rsignell-usgs Don't hit https://sensors.ioos.us for now. Use http://sensors.ioos.us.

**Comment by lukecampbell** [comment]
@rsignell-usgs you may need to clear HSTS for ioos

http://classically.me/blogs/how-clear-hsts-settings-major-browsers

enter `ioos.us` in the domain.

**Comment by rsignell-usgs** [comment]
Yep, this worked on Chrome:

**Comment by lukecampbell** [comment]
I'm glad it worked, it's unfortunate that this happened and our users are punished.

**Pull request merged**
