### PR TITLE
updated styling

### PR DESCRIPTION
**Pull request by kellydesent**

### CODE REVIEW

**Comment by Bobfrat** [comment]
thanks @kellydesent can you post a screenshot?

**Comment by kellydesent** [comment]
ioos-us-campure-search

**Comment by Bobfrat** [comment]
@mwengren what do you think?

**Comment by mwengren** [comment]
@Bobfrat @kellydesent I like it.  I don't find the blue to be too much, but let me send it around the office here first so others can take a look and get back to you.  They may prefer a gray color like the earlier expanded box.  

Since we have this more prominent search bar in place, I think we could safely remove the 'Data Discovery' tile as well, but I'll save that for another issue once this is settled.

**Pull request merged**
