### PR TITLE
update tile image

### PR DESCRIPTION
**Pull request by bnfish**

### CODE REVIEW

**Comment by mwengren** [comment]
@bnfish @kknee @lukecampbell Hi everyone, so clicking on the link for this most recent PR made me realize what my effect my tinkering in waffle.io has done.  Not sure how you all feel about the 'review' label, but this is being auto-generated by the waffle board here: https://waffle.io/ioos/ioos-us. 

The effect is that any PRs submitted show up in the review column before being merged.  Don't know if this is useful or too much of a nuisance.  You should be able to merge anything directly in Waffle if you want, just drag from 'Review' to 'Done' and it will be merged in Github.  This might be useful for some repos but since you all pretty much handle all the merging for this repo, maybe it's overkill.

I'd like to try it on the Catalog repos though.  You can also move issues from the Backlog to Ready to track what's being worked on at the moment or during a particular sprint and the 'ready' label will be applied.  Similarly, if you push a branch with an issue name in it 'issue-#59' for example, it'll show in the In Progress column/and the issue will get the 'in progress' label attached automatically.

Sorry for the lengthy comment...

**Comment by kknee** [comment]
@mwengren I was wondering about all those Review labels!

I agree that Waffle might be overkill here, we can discuss using it for Catalog when we kick that off.  We use Jira internally, so would need to figure out what works best for both internal and external tracking.

**Comment by mwengren** [comment]
Ok, removed (for new PRs).  I still have in place for the catalog and ckanext-ioos-theme repos, but those are a bit less active at the moment.

**Comment by birdage** [comment]
@bnfish this one good?

**Comment by lukecampbell** [comment]
screen shot 2016-07-01 at 9 12 30 am

**Pull request merged**
